CREATE DATABASE IF NOT EXISTS WebII;
USE WebII;

CREATE TABLE IF NOT EXISTS usuario (
	Id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NULL DEFAULT NULL,
    senha VARCHAR(50) NULL DEFAULT NULL
);